version: '3.8'

services:
  postgres-ead-authuser:
    image: postgres:13.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: ead-authuser
    ports:
      - 5430:5432
    volumes:
      - app-volume:/var/lib/postgresql/data

  postgres-ead-course:
    image: postgres:13.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: ead-course
    ports:
      - 5431:5432

volumes:
  app-volume: #
