server:
  port: 8082
  servlet:
    context-path: '/ead-course/'
  
spring:
  application:
    name: ead-course-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server
  datasource:
    url: jdbc:postgresql://localhost:5431/ead-course
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernat.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: ALWAYS
  rabbitmq:
    addresses: amqps://qxcsjgln:ks7OsmDW0TAI8kc119RuAclF6U-c_dtO@toad.rmq.cloudamqp.com/qxcsjgln

logging:
  level:
    com.ead: TRACE
    root: INFO

ead:
  ead:
    serviceRegistry:
      username: serviceregistry
      password: 'ead123sr'
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'
  broker:
    exchange:
      userEvent: ead.userevent
      notificationCommandExchange: ead.notificationcommand
    queue:
      userEventQueue:
        name: ead.userevent.ms.course
    key:
      notificationCommandKey: ms.notification

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost