server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sicrano3000/ead-config-server-repo
          default-label: main
          username: usuarioGit
          password: senhaGit

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://loclahost:8761/eureka'
  instance:
    hostname: localhost
